project_id = "kmyotdcxsodrxrrpsdpf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-menu-upload]
verify_jwt = false

[functions.dish-detection]
verify_jwt = false

[functions.save-scan]
verify_jwt = false