// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmyotdcxsodrxrrpsdpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteW90ZGN4c29kcnhycnBzZHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Mjc4NDksImV4cCI6MjA3NDEwMzg0OX0.9ZfYUczC0_L96RGkp89gMQIr-OBc6S249d5zCRNU2hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});